package com.technicalchallenge.validation;

import java.util.ArrayList;
import java.util.List;

/**
 * Holds all validation messages generated by one validation run.
 *
 * <p>This class acts as a container for {@link ValidationMessage} objects.
 * It provides helper methods to add messages and to check if any errors exist.
 */
public class ValidationResult {
    private final List<ValidationMessage> messages = new ArrayList<>();


    public void addError(String message) {
        messages.add(new ValidationMessage("ERROR", message));
    }

    public void addWarning(String message) {
        messages.add(new ValidationMessage("WARNING", message));
    }
    public boolean hasErrors() {
        return messages.stream().anyMatch(msg -> msg.type().equals("ERROR"));

    }
}
